# External gems
gems:
  - jekyll-sitemap

# Site settings
permalinks: /:title
title: 荒蛮之地
subtitle: "这里还没有被开垦哦"
email: abrasumentee@gmail.com
name: abrasumente
description: >
  深思熟虑
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://abrasumente233.github.io" # the base hostname & protocol for your site
cover: "assets/header_image.jpg"
logo: "assets/logo.png"
hl_style: "css/github.css"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

# Disqus comments
disqus_shortname: abcomment

# Google analytics
ga_tracking_id: "UA-66656181-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: 生活
    desc: "微博流水账式"

  - cat: 计算机
    desc: "也是流水账"

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share_url: http://twitter.com/share   # URL for sharing to the service (leave blank to not allow sharing)
#     share_title: ?text=                   # Title parameter for sharing URL
#     share_link: "&amp;url="               # Link parameter for sharing URL
social:
  - name: QQ
    icon: qq
    username: "345396594"
    url: http://wpa.qq.com/msgrd?v=3&uin=345396594&site=qq&menu=yes
    desc: Find me on QQ
    share_url:
    share_title:
    share_link:

  - name: GitHub
    icon: github
    username: abrasumente233
    url: https://github.com/abrasumente233
    desc: Fuck me on GitHub
    share_url:
    share_title:
    share_link:

  - name: SoundCloud
    icon: soundcloud
    username: abrasumente44
    url: https://soundcloud.com/abrasumente44
    desc: Follow me on SoundCloud
    share_url:
    share_title:
    share_link:

  - name: Steam
    icon: steam
    username: abrasumente44
    url: http://steamcommunity.com/id/abrasumente44/
    desc: Friend me on Steam
    share_url:
    share_title:
    share_link:
